all: lista_05_questao_1 lista_05_questao_2 lista_05_questao_3
	@echo Todas as questões compiladas.

lista_05_questao_1: lista_05_questao_1.c
	@gcc -std=c99 -O2 -lm lista_05_questao_1.c -o lista_05_questao_1
	@echo Questão 1 compilada.

lista_05_questao_2: lista_05_questao_2.c
	@gcc -std=c99 -O2 -lm lista_05_questao_2.c -o lista_05_questao_2
	@echo Questão 2 compilada.

lista_05_questao_3: lista_05_questao_3.c
	@gcc -std=c99 -O2 -lm lista_05_questao_3.c -o lista_05_questao_3
	@echo Questão 3 compilada.
