all: arvores grafos
	@echo Todos os trabalhos compilados.

arvores: arvores.c
	@gcc -g -std=c99 -O2 -lm arvores.c -o arvores
	@echo Trabalho de árvores compilado.

grafos: grafos.c
	@gcc -g -std=c99 -O2 -lm grafos.c -o grafos
	@echo Trabalho de grafos compilado.
